Repository GSG-G13/Abdullah-Khaled, pull requests merged in 2023-03, with the labels that each got.

#2 documentation
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/index.html
  public/js/main.js
  public/styles/style.css
  src/app.js
  src/index.js
Labels: documentation

#4 front-end
  public/index.html
  public/js/main.js
  public/styles/style.css
Labels: approved

#6 adding index.js
  package-lock.json
  package.json
  src/index.js
Labels: approved

#11 Final Fin
  public/js/main.js
  public/styles/style.css
Labels: waiting-approve
